// Generated by CoffeeScript 1.7.1
var PostBrunch;

module.exports = PostBrunch = (function() {
  PostBrunch.prototype.brunchPlugin = true;

  function PostBrunch(config) {
    var _ref;
    this.config = config;
    this.callback = (_ref = this.config.plugins.postBrunch) != null ? _ref : (function(_this) {
      return function() {};
    })(this);
  }

  PostBrunch.prototype.onCompile = function(generatedFiles) {
    this.callback.call(generatedFiles);
  };

  return PostBrunch;

})();
